name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        isMain:
          - ${{ github.ref == 'refs/heads/main' }}
        environment: [ development, production ]
        exclude:
          - isMain: false
            environment: production
    name: ${{ matrix.environment }}
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Build
        run: |
          echo VITE_API_URL=${{ secrets.API_URL }} > .env
          pnpm build
          mv dist ${{ matrix.environment }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.environment }}
          path: |
            ${{ matrix.environment }}
  deploy:
    strategy:
      fail-fast: false
      matrix:
        isMain:
          - ${{ github.ref == 'refs/heads/main' }}
        environment: [ development, production ]
        exclude:
          - isMain: false
            environment: production
    name: ${{ matrix.environment }}
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit
