name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.environment }}
          path: .
      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass
      - name: Deploy to ${{ inputs.environment }}
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          zip -r ${{ inputs.environment }}.zip ${{ inputs.environment }}/*
          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "rm -rf ${{ secrets.SERVER_PATH }}/*" || true
          sshpass -e scp -o StrictHostKeyChecking=no -P ${{ secrets.SERVER_PORT }} -r ${{ inputs.environment }}.zip ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}
          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.SERVER_PATH }} && unzip -o ${{ inputs.environment }}.zip && rm -f ${{ inputs.environment }}.zip"
          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "chmod -R 755 ${{ secrets.SERVER_PATH }} && chown -R www:www ${{ secrets.SERVER_PATH }}"
